### ISSUE TITLE
[Addition] Robust PCA Coherence Condition

### ISSUE THREAD

**Issue by passuf** [mohlerm/eth-cil-exam-summary#19]
Not sure if we discussed this before, but maybe we could add the coherence condition (Lecture 12, p.34).

**Comment by mohlerm** [comment]
Not sure, space is rather limited :/
Maybe we could remove some stuff from the 'Essentials' part and add more lecture content.
However, I can imagine some of these basics to turn out rather helpful at the exam...

**Comment by passuf** [comment]
I completely agree, there is still some space at the borders which can be filled by hand with custom stuff like this.

**Comment by mohlerm** [comment]
yes, totally :)

**Comment by mohlerm** [comment]
We could also compress PCA and SVD a bit more (and maybe also the first part about Matrix/Vector) to add some more content...

**Comment by passuf** [comment]
Nice, now we have quiet some space left! Maybe we should prioritize the remaining additions and make a feature freeze at some point, e.g. today at 16:00?

**Comment by mohlerm** [comment]
Yes, that sounds good.

**Comment by mohlerm** [comment]
I added page 34, however there is more on the following pages. But since the slides are rather vague about it I don't think it's relevant (e.g. what's the random sparsity pattern of cardinality m?).

I also did not add more details to ADMM for RPCA (e.g. individual primal minimization) since that's also rather complicated and difficult to describe in the limited space. If someone misses this he can simply annotate the summary on the borders.
